<?php

// изменение ссылок
function fts_pagination_url_outbound_alter(&$path, &$options, $original_path) {
	if(isset($options['query']['page'])) {
		$path = drupal_get_path_alias($path).'/page/'.($options['query']['page']+1);
		$options['alias'] = $path;
		$options['query'] = array();
	}
}

// вывод контента на страницах
function fts_pagination_url_inbound_alter(&$path, $original_path, $path_language) {
	global $_GET;
	$parts = explode('/page/', $original_path);
	if( isset($parts[1]) && ctype_digit($parts[1]) && $parts[0] != 'node' ) {
			$path_info = path_load(array('alias' => $parts[0]));
			if ($path_info['source']) {
				$path = $path_info['source'];
			} else {
				$path = $parts[0];
			}
			$_GET['page'] = $parts[1] - 1;
			// переменная в пост для проверки переадресации
			$_POST['custompagination'] = TRUE;
	}
	// переадресация 301 при нахождении пользователя на ?page=
	if (!isset($_POST['custompagination'] )) {
		if (isset($_GET['page'])) {
			$goto_path = $original_path.'/page/'.($_GET['page']+1);
			drupal_goto($goto_path,array(),301);
		}
	}
}